name: Hello World Docker

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./hello-world-docker-action
        id: hello-action
      - run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
